[package]
name = "ray_tracing"
version = "2.0.0"
authors = ["mango0110 <1119369173@qq.com>"]
edition = "2018"

[dependencies]
rand = "0.8"
lazy_static = "1"
image = "0.23"

thread_pool = { git = "https://github.com/dahai-f/thread_pool.git" }